config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'pages#home'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
    registrations: :registrations,
    omniauth_callbacks: :omniauth_callbacks,
  }

  namespace :api do
    resources :focuses, only: [:index]
  end

  get '/old-admin' => 'old_admin/dashboard#index'

  namespace :admin do
    resources :contact_messages, only: [:index, :show]
  end

  namespace :profile do
    scope :edit do
      get 'social' => 'social_profiles_connection#show'
      scope :social, as: :link do
        delete 'pinterest' => 'pinterest_link#destroy'
        delete 'twitter' => 'twitter_link#destroy'
        delete 'facebook' => 'facebook_link#destroy'
        delete 'instagram' => 'instagram_link#destroy'
        delete 'vine' => 'vine#destroy'
        resources :vine, only: [:new, :create]
      end
      get 'basic_info' => 'basic_info#edit'
      patch 'basic_info' => 'basic_info#update'
      get 'interests' => 'interests#edit'
      patch 'interests' => 'interests#update'
      get 'press' => 'press#edit'
      patch 'press' => 'press#update'
      get 'clients' => 'clients#edit'
      patch 'clients' => 'clients#update'
    end
    get 'search' => 'search#new'
    get 'search/results' => 'search#index'
  end

  resources :profiles, only: [:show]
  resources :contact_messages, only: [:create, :destroy]
  resources :influencer_lists, path: :lists
  resources :list_memberships, only: [:create, :destroy]
  resources :bulk_list_memberships, only: [:create]
  resources :omniauth_add_email, only: [:new, :create]
  resources :organizations
  resources :organization_memberships, only: [:create, :destroy]
  resources :organization_list_memberships, only: [:create, :destroy]
  post "list-copy" => "list_copies#create"

  get 'content-creators' => 'pages#creators'
  get 'brands-agencies' => 'pages#brands'
  get "about" => "pages#about"
  get "team" => "pages#team"
  get "contact" => "pages#contact"
  get "faq" => "pages#faq"
  get "jobs" => "pages#jobs"
  get "terms" => "pages#terms"
  get "privacy" => "pages#privacy"
  get "about" => "pages#about"
end

app/models/user.rb
class User < ActiveRecord::Base
  # HACK: Because the sign up page requires information that needs to make its
  # way to the corresponding Profile, we need a way to temporarily store those
  # attributes until the create_profile after_action is called. This can
  # eventually be refactored into an action object.
  attr_accessor :name, :username

  has_many :influencer_lists, dependent: :destroy
  has_one :profile

  after_create :create_profile

  validates :password, length: { in: 6..128 }, on: :update, allow_blank: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable,
         omniauth_providers: [:facebook, :instagram, :twitter, :pinterest]

  def create_profile
    profile || Profile.create(user_id: id, name: name, username: username)
  end

  def profile
    reload
    super()
  end

  def has_account?
    true
  end

  # Devise, I hate you so much.
  def update_without_password(params, *options)
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def owns_list?(list)
    list.owner == self
  end

  def can_manage_list?(list)
    return true if admin?
    return true if list.owner == self

    list.organizations.where(id: profile.organization_ids).any?
  end

  protected

  def confirmation_required?
    facebook_token? ? false : true
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def edit
    @user = User.find(current_user)
    @user.presses.build
    @user.clients.build
  end

  def update
    @user = User.find(current_user)
    successfully_updated = if needs_password?(@user, params)

      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to edit_user_registration_path
    else
      render "edit"
    end
  end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present? ||
      params[:user][:password_confirmation].present?
  end
end

app/controllers/users/vines_controller.rb
class Users::VinesController < ApplicationController
  def new
  end

  def create
    current_user.vine_email = params[:vine][:email]
    current_user.vine_password = params[:vine][:password]
    current_user.save
    redirect_to users_social_path
  end

   def destroy
    current_user.vine_email = nil
    current_user.vine_password = nil
    current_user.save
    redirect_to users_social_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    if current_user.admin?
      @available_lists = InfluencerList.all - @user.lists_member_of
      @available_organizations = Organization.all - @user.organizations
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_admin_user_options.erb
<div class="row">
  <hr>
  <% if current_user.admin? %>
    <div class="col-md-4">
      <p>Add User to list</p>
      <%= simple_form_for(:list_membership, url: list_memberships_path) do |f| %>
        <%= f.hidden_field :profile_id, value: @user.id %>
        <%= f.input :influencer_list_id, as: :select, label: false, collection: @available_lists, input_html: {class: "flat-form-control"} %>
        <%= f.submit "Add" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <p>Add User to Organization</p>
      <%= simple_form_for(:organization_membership, url: organization_memberships_path) do |f| %>
        <%= f.hidden_field :profile_id, value: @user.id %>
        <%= f.input :organization_id, as: :select, label: false, collection: @available_organizations, input_html: {class: "flat-form-control"} %>
        <%= f.submit "Add" %>
      <% end %>
    </div>
  <% end %>
  <% if @user.organizations.any? %>
    <div class="col-md-4">
      <div class="row">
        <p>Organizations:</p>
        <ul>
          <% @user.organizations.each do |organization| %>
            <li><p><%= link_to organization.name, organization %></p></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<% if @user.influencer_lists.any? %>
  <div class="col-md-4">
    <div class="row">
      <p>Lists</p>
      <ul>
        <% @user.influencer_lists.each do |list| %>
          <li><p><%= link_to list_memberships_path %></p></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_admin_user_options.html.erb
<div class="row">
  <% if current_user.admin? %>
    <hr>
    <div class="col-md-4">
      <p>Add User to list</p>
      <%= simple_form_for(:list_membership, url: list_memberships_path) do |f| %>
        <%= f.hidden_field :profile_id, value: @user.id %>
        <%= f.input :influencer_list_id, as: :select, label: false, collection: @available_lists, input_html: { class: "flat-form-control", id: 'test-influencer-list-select' } %>
        <%= f.submit "Add", id: 'test-add-to-influencer-list-submit' %>
      <% end %>
    </div>
    <div class="col-md-4">
      <p>Add User to Organization</p>
      <%= simple_form_for(:organization_membership, url: organization_memberships_path) do |f| %>
        <%= f.hidden_field :profile_id, value: @user.id %>
        <%= f.input :organization_id, as: :select, label: false, collection: @available_organizations, input_html: {class: "flat-form-control", id: 'test-add-to-organization-form'} %>
        <%= f.submit "Add", id: 'test-add-to-organization-submit' %>
      <% end %>
    </div>
  <% end %>
  <% if @user.organizations.any? %>
    <div class="col-md-4">
      <div class="row">
        <p>Organizations:</p>
        <ul>
          <% @user.organizations.each do |organization| %>
            <li><p><%= link_to organization.name, organization %></p></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<% if @user.influencer_lists.any? %>
  <div class="col-md-4">
    <div class="row">
      <p>Lists</p>
      <ul>
        <% @user.influencer_lists.each do |list| %>
          <li><p><%= link_to list_memberships_path %></p></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_follower_counts.html.erb
<% if @user.send("#{social}_follower_count") %>
  <ul class="user-social-follower-counts">
    <li class="user-social-follower-count col-md-1">
      <%= image_tag("#{social}_logo_sq.svg", class: 'user-social-icon', alt: "#{social} Logo") %>
      <%= truncated_count(@user.send("#{social}_follower_count")) %>
    </li>
  </ul>
<% end %>

app/views/users/show.html.erb
<div class="container user">
  <header class="row user-row">
    <div class="col-sm-4">
      <%= image_tag(@user.picture.url(:medium), alt: 'Profile Pic') %>
    </div>

    <div class="col-sm-8">
      <h2><%= @user.name %></h2>

      <h5><% if @user.focuses.present? %>
        <%= @user.focuses.pluck(:name).join(', ') %>
      <% elsif current_user == @user %>
        <%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-plus-sign green" title="Add Website"></span> Add your skills
        <% end %>
      <% end %></h5>

      <h4><% if @user.bio.present? %>
        <%= @user.bio  %>
      <% elsif current_user == @user %>
        <%= link_to edit_user_registration_path do %>
          <span class="glyphicon glyphicon-plus-sign green" title="Add Bio"></span> Add your Bio
        <% end %>
      <% end %></h4>

      <ul class="user-meta">
        <li data-role="geo-contact">
          <% if @user.city.present? %>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <%= @user.city %>
          <% elsif current_user == @user %>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-plus-sign green" title="Add City"></span> add your city
            <% end %>
          <% end %>
        </li>

        <li>
          <% if @user.website.present? %>
            <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
            <%= link_to @user.website, "http://#{@user.website}" %>
          <% elsif current_user == @user %>
            <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-plus-sign green" title="Add Website"></span> add your website
            <% end %>
          <% end %>
        </li>
        <% if signed_in_admin? || current_user == @user %>
          <li>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            <%= mail_to @user.email, @user.email %>
          </li>
        <% end %>
      </ul>
    </div>
  </header>

  <%= render 'admin_user_options'%>

  <div class="row user-row user-total-follower-row">
    <dl class="user-total-follower-count col-sm-4">
      <dt>TOTAL FOLLOWERS:</dt>
      <dd><%= number_with_delimiter(@user.total_follower_count) %></dd>
    </dl>

    <% User::SOCIAL_PLATFORMS.each do |social| %>
      <%= render 'follower_counts', social: social %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm-4 user-subsection">
      <h2>Interests</h2>
      <% if @user.interests.present? %>
        <% @user.interests.each do |interest| %>
          <button type="button" class="btn btn-default btn-interests"><%= interest.name %></button>
        <% end %>
      <% elsif current_user == @user %>
        <%= link_to profile_interests_path do %>
          <h4 class="text-center">Add Interests</h4>
          <h4 class="text-center"><span class="glyphicon glyphicon-plus-sign green" title="Add Interests"></span></h4>
        <% end %>
      <% end %>
      <p><%= @user.special_interests %></p>
    </div>

    <div class="col-sm-4 user-subsection">
      <h2>Press</h2>
      <% if @user.press.present? %>
        <% @user.press.each do |press| %>
          <h5><%= link_to press.name, press.url %></h5>
        <% end %>
      <% elsif current_user == @user %>
        <%= link_to profile_press_path do %>
          <h4 class="text-center">Add Press</h4>
          <h4 class="text-center"><span class="glyphicon glyphicon-plus-sign green" title="Add Press"></span></h4>
        <% end %>
      <% end %>
    </div>

    <div class="col-sm-4 user-subsection">
      <h2>Clients</h2>
      <% if @user.clients.present? %>
        <% @user.clients.each do |client| %>
          <h5><%= link_to client.name, client.url %></h5>
        <% end %>
      <% elsif current_user == @user %>
        <%= link_to profile_clients_path do %>
          <h4 class="text-center">Add Clients</h4>
          <h4 class="text-center"><span class="glyphicon glyphicon-plus-sign green" title="Add Clients"></span></h4>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @user.instagram_media %>
    <h6>Recent Instagram Posts</h6>
    <div class="row user-social-instagram">
      <% @user.instagram_media.first(9).each do |instagram_picture| %>
        <div class="col-sm-6 col-md-4">
          <%= link_to(image_tag(instagram_picture['images']['standard_resolution']['url'], class: 'platform-media'), instagram_picture['link']) %>
          <ul class="user-post-icons">
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-thumbs-up pink" aria-hidden="true"></span>
              <%= truncated_count(instagram_picture['likes']['count'].round) %>
            </li>
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-comment pink" aria-hidden="true"></span>
              <%= truncated_count(instagram_picture['comments']['count'].round) %>
          </ul>
        </div>
      <% end %>
    </div>
  <% elsif current_user == @user %>
    <h6>Recent Instagram Posts</h6>
    <%= link_to profile_social_path do %>
      <h4 class="text-center">Connect your Instagram profile to showcase your latests posts.</h4>
      <h4 class="text-center"><span class="glyphicon glyphicon-plus-sign green" title="Connect Vine"></span></h4>
    <% end %>
  <% end %>

  <% if @user.vine_media %>
    <h6>Recent Vine Videos</h6>
    <div class="row">
      <% @user.vine_media.first(9).each do |vine| %>
        <div class="col-sm-6 col-md-4">
          <%= videojs_tag(vine.videoUrl, class: 'platform-video', thumbnail: vine.thumbnailUrl) %>
          <ul class="user-post-icons">
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-thumbs-up pink" aria-hidden="true"></span>
              <%= vine.likes['count'] %>
            </li>
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-refresh pink" aria-hidden="true"></span>
              <%= vine.reposts['count'] %>
            </li>
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-play-circle pink" aria-hidden="true"></span>
              <%= truncated_count(vine.loops['count'].round) %>
            </li>
            <li class="user-post-icon">
              <span class="glyphicon glyphicon-comment pink" aria-hidden="true"></span>
              <%= truncated_count(vine.comments['count'].round) %>
            </li>
          </ul>
        </div>
      <% end %>
    <% elsif current_user == @user %>
    <h6>Recent Vine Videos</h6>
      <%= link_to profile_social_path do %>
        <h4 class="text-center">Connect your Vine profile to showcase your latests posts.</h4>
        <h4 class="text-center"><span class="glyphicon glyphicon-plus-sign green" title="Connect Vine"></span></h4>
      <% end %>
    <% end %>
  </div>
</div>