config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'pages#home'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
    registrations: :registrations,
    omniauth_callbacks: :omniauth_callbacks,
  }

  namespace :api do
    resources :focuses, only: [:index]
  end

  get '/old-admin' => 'old_admin/dashboard#index'

  namespace :admin do
    resources :contact_messages, only: [:index, :show]
  end

  namespace :profile do
    scope :edit do
      get 'social' => 'social_profiles_connection#show'
      scope :social, as: :link do
        delete 'pinterest' => 'pinterest_link#destroy'
        delete 'twitter' => 'twitter_link#destroy'
        delete 'facebook' => 'facebook_link#destroy'
        delete 'instagram' => 'instagram_link#destroy'
        delete 'vine' => 'vine#destroy'
        resources :vine, only: [:new, :create]
      end
      get 'basic_info' => 'basic_info#edit'
      patch 'basic_info' => 'basic_info#update'
      get 'interests' => 'interests#edit'
      patch 'interests' => 'interests#update'
      get 'press' => 'press#edit'
      patch 'press' => 'press#update'
      get 'clients' => 'clients#edit'
      patch 'clients' => 'clients#update'
    end
    get 'search' => 'search#new'
    get 'search/results' => 'search#index'
  end

  resources :profiles, only: [:show]
  resources :contact_messages, only: [:create, :destroy]
  resources :influencer_lists, path: :lists
  resources :list_memberships, only: [:create, :destroy]
  resources :bulk_list_memberships, only: [:create]
  resources :omniauth_add_email, only: [:new, :create]
  resources :organizations
  resources :organization_memberships, only: [:create, :destroy]
  resources :organization_list_memberships, only: [:create, :destroy]
  post "list-copy" => "list_copies#create"

  get 'content-creators' => 'pages#creators'
  get 'brands-agencies' => 'pages#brands'
  get "about" => "pages#about"
  get "team" => "pages#team"
  get "contact" => "pages#contact"
  get "faq" => "pages#faq"
  get "jobs" => "pages#jobs"
  get "terms" => "pages#terms"
  get "privacy" => "pages#privacy"
  get "about" => "pages#about"
end

app/controllers/profile/social_profiles_connection_controller.rb
class Profile::SocialProfilesConnectionController < ApplicationController
  before_action :authenticate_user!

  layout 'application_with_sidebar'

  def show
    @profile = current_user.profile
  end
end

app/views/social_profiles_connection/show.html.erb
<%= render 'layouts/user_navigation' %>
  <div class="col-md-6 col-md-offset-4">
    <h1>Social Profiles</h1>
    <h2>Connect your accounts</h2>
    <h1><%= current_user.total_social_count %></h1>
    <p>Total Reach</p>

  <p>Connect at least 2 accounts.</p>
    <div class="well">
     <h2>
      <%= image_tag("vine_logo.svg", :size => '30', :alt => "Vine Logo") %> Vine
       <% if current_user.vine_password? %>
       <p>followed by: <%= current_user.vine_follower_count %></p>
       <%=link_to image_tag("green_check_icon.svg", size: "30x30"), vine_authentication_path, method: :delete %>
       <% else %>
        <%= link_to 'Connect', vine_authentication_path, class: "btn btn-primary btn-lg" %>
       <% end %>

     </h2>
    </div>

    <div class="well">
     <h2>
      <%= image_tag("twitter_logo.svg", :size => '30', :alt => "Twitter Logo") %> Twitter
       <% if current_user.twitter_token? %>
       <p>followed by: <%= current_user.twitter_follower_count %></p>

       <%=link_to image_tag("green_check_icon.svg", size: "30x30"), twitter_link_destroy_path, method: :delete %>
       <% else %>
        <%= link_to 'Connect', user_omniauth_authorize_path(:twitter), class: "btn btn-primary btn-lg" %>
       <% end %>

     </h2>
    </div>

    <div class="well">
     <h2>
       <%= image_tag("instagram_logo.svg", :size => '30', :alt => "Vine Logo") %>
       Instagram
       <% if current_user.instagram_token? %>
       <p>followed by: <%= current_user.instagram_follower_count %></p>

       <%=link_to image_tag("green_check_icon.svg", size: "30x30"), instagram_link_destroy_path, method: :delete %>
       <% else %>
        <%= link_to 'Connect', user_omniauth_authorize_path(:instagram), class: "btn btn-primary btn-lg" %>
       <% end %>
     </h2>
    </div>

    <div class="well">
     <h2>
       <%= image_tag("facebook_logo.svg", :size => '30', :alt => "Facebook Logo") %> Facebook
       <% if current_user.facebook_token? %>
        <p>followed by: <%= current_user.facebook_follower_count %></p>
        <%=link_to image_tag("green_check_icon.svg", size: "30x30"), facebook_link_destroy_path, method: :delete %>
       <% else %>
        <%= link_to 'Connect', user_omniauth_authorize_path(:facebook), class: "btn btn-primary btn-lg" %>
       <% end %>
       <!--<button type="button" class="btn btn-primary btn-lg">Connect</button>-->
     </h2>
    </div>

    <div class="well">
     <h2>
        <%= image_tag("pinterest_logo.svg", :size => '30', :alt => "Pinterest Logo") %> Pinterest
       <% if current_user.pinterest_token? %>
       <p>followed by: <%= current_user.pinterest_follower_count %></p>

       <%=link_to image_tag("green_check_icon.svg", size: "30x30"), pinterest_link_destroy_path, method: :delete %>
       <% else %>
        <%= link_to 'Connect', user_omniauth_authorize_path(:pinterest), class: "btn btn-primary btn-lg" %>
       <% end %>
     </h2>
    </div>

  </div>