config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'pages#home'

  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/sidekiq'
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
    registrations: :registrations,
    omniauth_callbacks: :omniauth_callbacks,
  }

  namespace :api do
    resources :focuses, only: [:index]
  end

  get '/old-admin' => 'old_admin/dashboard#index'

  namespace :admin do
    resources :contact_messages, only: [:index, :show]
  end

  namespace :profile do
    scope :edit do
      get 'social' => 'social_profiles_connection#show'
      scope :social, as: :link do
        delete 'pinterest' => 'pinterest_link#destroy'
        delete 'twitter' => 'twitter_link#destroy'
        delete 'facebook' => 'facebook_link#destroy'
        delete 'instagram' => 'instagram_link#destroy'
        delete 'vine' => 'vine#destroy'
        resources :vine, only: [:new, :create]
      end
      get 'basic_info' => 'basic_info#edit'
      patch 'basic_info' => 'basic_info#update'
      get 'interests' => 'interests#edit'
      patch 'interests' => 'interests#update'
      get 'press' => 'press#edit'
      patch 'press' => 'press#update'
      get 'clients' => 'clients#edit'
      patch 'clients' => 'clients#update'
    end
    get 'search' => 'search#new'
    get 'search/results' => 'search#index'
  end

  resources :profiles, only: [:show]
  resources :contact_messages, only: [:create, :destroy]
  resources :influencer_lists, path: :lists
  resources :list_memberships, only: [:create, :destroy]
  resources :bulk_list_memberships, only: [:create]
  resources :omniauth_add_email, only: [:new, :create]
  resources :organizations
  resources :organization_memberships, only: [:create, :destroy]
  resources :organization_list_memberships, only: [:create, :destroy]
  post "list-copy" => "list_copies#create"

  get 'content-creators' => 'pages#creators'
  get 'brands-agencies' => 'pages#brands'
  get "about" => "pages#about"
  get "team" => "pages#team"
  get "contact" => "pages#contact"
  get "faq" => "pages#faq"
  get "jobs" => "pages#jobs"
  get "terms" => "pages#terms"
  get "privacy" => "pages#privacy"
  get "about" => "pages#about"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :organization_memberships, dependent: :destroy
  has_many :profiles, through: :organization_memberships
  has_many :organization_list_memberships, dependent: :destroy
  has_many :influencer_lists, through: :organization_list_memberships

  validates :name, presence: true, uniqueness: true

  def add_profile(profile)
    if profiles.exclude?(profile)
      profiles << profile
    end
  end

  def add_list(list)
    if influencer_lists.exclude?(list)
      influencer_lists << list
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authorize_admin!

  layout 'application_with_sidebar'

  def show
    @organization = find_organization
    @available_lists = InfluencerList.all - @organization.influencer_lists
  end

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to @organization
    else
      render :new
    end
  end

  def edit
    @organization = find_organization
  end

  def update
    @organization = find_organization

    if @organization.update(organization_params)
      redirect_to @organization
    else
      render :edit
    end
  end

  def destroy
    organization = find_organization
    organization.destroy
    redirect_to organizations_path, alert: "\"#{organization.name}\" deleted!"
  end

  private

  def find_organization
    Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/organizations/_form.html.erb
<%= simple_form_for @organization do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/organizations/_organization.html.erb
<tr>
  <td><h4><%= link_to organization.name.capitalize, organization %></h4></td>

  <td>
    <% organization.profiles.each do |profile| %>
        <%= link_to image_tag(profile.picture.url(:medium), :size => '40', alt: 'Profile Pic'), profile_path(id: profile.id) %>
    <% end %>
  </td>

  <td>
    <h4>
      <%= link_to edit_organization_path(organization) do %>
        <span class="glyphicon glyphicon-pencil pink" title="Edit Org Name"></span>
      <% end %>
      <%= link_to organization, method: :delete do %>
        <span class="glyphicon glyphicon-trash pink" title="Delete Org"></span>
      <% end %>
    </h4>
  </td>
</tr>

app/views/organizations/edit.html.erb
<h2>Rename an organization</h2>

<%= render "form", organization: @organization %>

<div class="actions">
  <%= link_to 'Back', :back, class: 'btn btn-default' %>
</div>

app/views/organizations/index.html.haml
= render "layouts/index_organization_nav_bar"
.sub-layout
  .table-responsive
    %table.table.table-striped
      %thead
        %tr
          %th Organization Name
          %th Members
      %tbody
        = render @organizations

app/views/organizations/new.html.erb
  <h2>Create a new organization</h2>

  <%= render "form", organization: @organization %>

app/views/organizations/show.html.haml
= render "layouts/organization_nav_bar"
- if current_user.admin?
  %p
    = link_to edit_organization_path(@organization), class: 'glyphicon glyphicon-pencil', id: 'test-rename-organization' do
      %span{:title => "Rename Organization"}
  %p
    = link_to @organization, method: :delete, class: 'glyphicon glyphicon-trash', id: 'test-delete-organization' do
      %span{:title => "Delete Organization"}
%h2 Lists
- if current_user.admin?
  %p Add list
  = simple_form_for(:organization_list_membership, url: organization_list_memberships_path) do |f|
    = f.hidden_field :organization_id, value: @organization.id
    = f.input :influencer_list_id, as: :select, collection: @available_lists
    = f.submit "Add List", class: 'btn btn-default'
%ul
  - @organization.influencer_lists.each do |list|
    %li{class: "influencer-list-#{list.id}"}
      .row
        .col-sm-5.col-md-5
          = link_to list.name, influencer_list_path(list), class: "client-input"
        .col-sm-1.col-md-1
          = link_to organization_list_membership_path(list.organization_membership(@organization)), method: :delete, class: "glyphicon glyphicon-remove-circle", id: 'test-remove-membership' do
            %span{:title => "Remove List"}

%h2 Members of Organization
%ul
  - @organization.profiles.each do |profile|
    %li
      = link_to image_tag(profile.picture.url(:medium), :size => '175', alt: 'Profile Pic'), profile_path(id: profile.id)
      %h4= link_to profile.name, profile_path(profile)
      %p
        - if profile.user
          %span.glyphicon.glyphicon-envelope{"aria-hidden" => "true"}
          = mail_to profile.user.email, profile.user.email
      %h5
        = link_to organization_membership_path(profile.organization_membership_in(@organization)), method: :delete, role: 'remove_user_from_organization', class: 'glyphicon glyphicon-remove-circle' do
          %span{:title => "Remove Member From Organization"}
            %p Remove Profile